### ISSUE TITLE
longitude sorting

### ISSUE THREAD

**Issue by mafla** [CAB-LAB/CABLAB.jl#19]
If I type getCubeData(c, variable=var, latitude=(-10, 12), longitude=(-80, -65)) it works fine, if I would swap the order to the two longitude bounds it gives me an error.

**Comment by Torminator** [comment]
So you mean getCubeData(c, variable=var, latitude=(-10, 12), longitude=(-65, -80)) ? 
In that case:
     Data Cube view with the following dimensions
     Lon                 Axis with 0 Elements from -65.00045999999999 to -65.08379299999999
     Lat                 Axis with 263 Elements from 12.000311999999994 to -9.832934000000009
     Time                Axis with 506 Elements from 2001-01-01T00:00:00 to 2011-12-27T00:00:00
the Longitude Axis has no Elements.

**Comment by mafla** [comment]
yes, and this does not make much sense to me. It should not matter if I go from the larger to the smaller value or vice versa.

**Comment by meggart** [comment]
Yes, will fix this after the PM.

**Comment by meggart** [comment]
This is not as straight forward as I thought. If we automatically sort the entered longitudes, what do we do when a user explicitly wants a cutout intersecting the date line? So how can we determine if (170,-170) means a small box over the dateline or a large one around the globe. 
I have to admit that currently dateline intersections are not supported, either, but it was planned for the future. Maybe @forman will comment since we might want to remain compatible with the python interface.

**Comment by mafla** [comment]
Oh, I see - but I guess that on the long-term we should enable cross date line cutouts. Maybe we should have a simple warning for now...

**Comment by meggart** [comment]
Fixed through d6ae6f768f29 an error is thrown when longitudes are passed in the wrong order. Latitudes are automatically sorted.
